env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    gh_token: "ENCRYPTED[d33aa6d3c484d512e2e653158899c442820ed2d1991157f423e67959292d0297a1f24eae79e5d0e807d67d0fdc31c496]"

task:
    name: aosp
    timeout_in: 260m
    container:
      image: atomxorg/ubuntu:latest
      cpu: 8
      memory: 32G
      commands:
      - sudo apt-get install gpg
      - rm -rf ~/.repoconfig
    download_ccache_background_script: # To download ccache in background
      - /noclone3 bash download_ccache # Ccache download script
    sync_script:
      - /noclone3 bash sync
    build_script:
      - /noclone3 bash build
    upload_ccache_script: # Upload ccache to cloud foreground
      - /noclone3 bash upload_ccache # Ccache uploading script
